export const ERROR_CODES = {
  // Common
  INTERNAL_ERROR: "INTERNAL_ERROR",
  CLIENT_FACTORY_ERROR: "CLIENT_FACTORY_ERROR",

  // Config/Secrets
  CONFIG_ERROR: "CONFIG_ERROR",
  CONFIG_NOT_FOUND: "CONFIG_NOT_FOUND",
  CONFIG_AUTH_NOT_FOUND: "CONFIG_AUTH_NOT_FOUND",
  CONFIG_READ_FAILED: "CONFIG_READ_FAILED",
  REGISTERED_APPS_READ_FAILED: "REGISTERED_APPS_READ_FAILED",
  REGISTERED_APPS_WRITE_FAILED: "REGISTERED_APPS_WRITE_FAILED",
  REGISTERED_APP_DUPLICATE: "REGISTERED_APP_DUPLICATE",
  REGISTERED_APP_NOT_FOUND: "REGISTERED_APP_NOT_FOUND",
  REGISTERED_APP_STORE_INFO_MISSING: "REGISTERED_APP_STORE_INFO_MISSING",

  // Service guards
  CONFIG_NOT_FOUND_SKIP: "CONFIG_NOT_FOUND",
  IDENTIFIER_MISSING: "IDENTIFIER_MISSING",
  NO_DATA_FOUND: "NO_DATA_FOUND",

  // App resolution
  APP_IDENTIFIER_MISSING: "APP_IDENTIFIER_MISSING",
  APP_NOT_FOUND: "APP_NOT_FOUND",
  APP_RESOLUTION_FAILED: "APP_RESOLUTION_FAILED",

  // App Store factory
  APP_STORE_CLIENT_CONFIG_MISSING: "APP_STORE_CLIENT_CONFIG_MISSING",
  APP_STORE_BUNDLE_ID_INVALID: "APP_STORE_BUNDLE_ID_INVALID",
  APP_STORE_CONFIG_LOAD_FAILED: "APP_STORE_CONFIG_LOAD_FAILED",
  APP_STORE_CONFIG_MISSING: "APP_STORE_CONFIG_MISSING",
  APP_STORE_ISSUER_ID_INVALID: "APP_STORE_ISSUER_ID_INVALID",
  APP_STORE_KEY_ID_INVALID: "APP_STORE_KEY_ID_INVALID",
  APP_STORE_PRIVATE_KEY_INVALID: "APP_STORE_PRIVATE_KEY_INVALID",
  APP_STORE_PRIVATE_KEY_FORMAT_INVALID: "APP_STORE_PRIVATE_KEY_FORMAT_INVALID",
  APP_STORE_CLIENT_CREATE_FAILED: "APP_STORE_CLIENT_CREATE_FAILED",

  // Google Play factory
  GOOGLE_PLAY_CLIENT_CONFIG_MISSING: "GOOGLE_PLAY_CLIENT_CONFIG_MISSING",
  GOOGLE_PLAY_PACKAGE_NAME_INVALID: "GOOGLE_PLAY_PACKAGE_NAME_INVALID",
  GOOGLE_PLAY_CONFIG_LOAD_FAILED: "GOOGLE_PLAY_CONFIG_LOAD_FAILED",
  GOOGLE_PLAY_CONFIG_MISSING: "GOOGLE_PLAY_CONFIG_MISSING",
  GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_INVALID:
    "GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_INVALID",
  GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_FORMAT_INVALID:
    "GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_FORMAT_INVALID",
  GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_PARSE_FAILED:
    "GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_PARSE_FAILED",
  GOOGLE_PLAY_CLIENT_CREATE_FAILED: "GOOGLE_PLAY_CLIENT_CREATE_FAILED",

  // App Store service
  APP_STORE_LIST_APPS_FAILED: "APP_STORE_LIST_APPS_FAILED",
  APP_STORE_FETCH_APP_INFO_FAILED: "APP_STORE_FETCH_APP_INFO_FAILED",
  APP_STORE_GET_LATEST_VERSION_FAILED: "APP_STORE_GET_LATEST_VERSION_FAILED",
  APP_STORE_VERSION_NOT_EDITABLE: "APP_STORE_VERSION_NOT_EDITABLE",
  APP_STORE_UPDATE_RELEASE_NOTES_PARTIAL:
    "APP_STORE_UPDATE_RELEASE_NOTES_PARTIAL",
  APP_STORE_UPDATE_RELEASE_NOTES_FAILED:
    "APP_STORE_UPDATE_RELEASE_NOTES_FAILED",
  APP_STORE_PULL_RELEASE_NOTES_FAILED: "APP_STORE_PULL_RELEASE_NOTES_FAILED",
  APP_STORE_CREATE_VERSION_FAILED: "APP_STORE_CREATE_VERSION_FAILED",
  APP_STORE_PUSH_FAILED: "APP_STORE_PUSH_FAILED",
  APP_STORE_STATE_ERROR: "APP_STORE_STATE_ERROR",
  APP_STORE_CREATE_VERSION_FOR_STATE_ERROR_FAILED:
    "APP_STORE_CREATE_VERSION_FOR_STATE_ERROR_FAILED",
  APP_STORE_VERIFY_AUTH_FAILED: "APP_STORE_VERIFY_AUTH_FAILED",

  // Google Play service
  GOOGLE_PLAY_FETCH_APP_INFO_FAILED: "GOOGLE_PLAY_FETCH_APP_INFO_FAILED",
  GOOGLE_PLAY_GET_LATEST_RELEASE_FAILED:
    "GOOGLE_PLAY_GET_LATEST_RELEASE_FAILED",
  GOOGLE_PLAY_RELEASE_NOTES_EMPTY: "GOOGLE_PLAY_RELEASE_NOTES_EMPTY",
  GOOGLE_PLAY_UPDATE_RELEASE_NOTES_PARTIAL:
    "GOOGLE_PLAY_UPDATE_RELEASE_NOTES_PARTIAL",
  GOOGLE_PLAY_UPDATE_RELEASE_NOTES_FAILED:
    "GOOGLE_PLAY_UPDATE_RELEASE_NOTES_FAILED",
  GOOGLE_PLAY_PULL_RELEASE_NOTES_FAILED:
    "GOOGLE_PLAY_PULL_RELEASE_NOTES_FAILED",
  GOOGLE_PLAY_CREATE_VERSION_FAILED: "GOOGLE_PLAY_CREATE_VERSION_FAILED",
  GOOGLE_PLAY_PUSH_FAILED: "GOOGLE_PLAY_PUSH_FAILED",
  GOOGLE_PLAY_VERIFY_AUTH_FAILED: "GOOGLE_PLAY_VERIFY_AUTH_FAILED",

  // ASO data/files
  ASO_GOOGLE_PLAY_DATA_PARSE_FAILED: "ASO_GOOGLE_PLAY_DATA_PARSE_FAILED",
  ASO_APP_STORE_DATA_PARSE_FAILED: "ASO_APP_STORE_DATA_PARSE_FAILED",
  ASO_DATA_SAVE_FAILED: "ASO_DATA_SAVE_FAILED",
  ASO_IMAGE_DOWNLOAD_FAILED: "ASO_IMAGE_DOWNLOAD_FAILED",
  ASO_LOCAL_ASSET_NOT_FOUND: "ASO_LOCAL_ASSET_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
